version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    container_name: fatihdgntodo-sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: uKvKWLWebXu9GpMw
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
  api:
    image: ${DOCKER_REGISTRY-}fatihdgntodo-api
    build:
      context: .
      dockerfile: Fatihdgn.Todo.API/Dockerfile
    ports:
      - 8180:443
      - 8181:80
    depends_on:
      - sqlserver
  app:
    image: ${DOCKER_REGISTRY-}fatihdgntodo-app
    build:
      context: ./Fatihdgn.Todo.Web
      dockerfile: Dockerfile
    ports:
      - 8080:4200
    depends_on:
      - api
volumes:
  mssql-data: